artifacts_root: artifacts


data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: "manual"
    local_data_file: artifacts/data.zip
    unzip_dir: artifacts/raw_data




data_validation:
    root_dir: artifacts/data_validation
    data_dir: artifacts/raw_data/train.csv
    status_file: artifacts/data_validation/status.txt
    


data_transformation:
    root_dir: artifacts/data_transformation
    data_dir: artifacts/raw_data/train.csv 
    schema_file_path: schema.yaml



model_trainer:
    root_dir: artifacts/model_trainer
    train_data_dir: artifacts/data_transformation/train_transformed.csv
    test_data_dir: artifacts/data_transformation/test_transformed.csv
    model_name: model.joblib
    



model_evaluation:
    root_dir: artifacts/model_evaluation 
    test_data_dir: artifacts/data_transformation/test_transformed.csv   
    model_dir: artifacts/model_trainer/model.joblib
    metrics_file_name: metrics.json
    


prediction:
    root_dir: artifacts/prediction
    model_dir: artifacts/model_trainer/model.joblib
    input_file: artifacts/raw_data/test.csv
    output_file: artifacts/prediction/predicted_output.csv
    pipeline_path: artifacts/data_transformation/pipeline.joblib  