artifacts_root: artifacts


data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: "manual"
    local_data_file: artifacts/data.zip
    unzip_dir: artifacts/raw_data




data_validation:
    root_dir: artifacts/data_validation
    data_dir: artifacts/raw_data/train.csv
    status_file: artifacts/data_validation/status.txt
    


data_transformation:
    root_dir: artifacts/data_transformation
    data_dir: artifacts/raw_data/train.csv 
    schema_file_path: schema.yaml



model_trainer:
    root_dir: artifacts/model_trainer
    train_data_dir: artifacts/data_transformation/train.csv
    test_data_dir: artifacts/data_transformation/test.csv
    model_name: model.joblib
    
    