artifacts_root: artifacts


data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: "manual"
    local_data_file: artifacts/data.zip
    unzip_dir: artifacts/raw_data


artifacts_rootst: artifacts

data_validation:
    root_dir: artifacts/data_validation
    data_dir: artifacts/raw_data/train.csv
    status_file: artifacts/data_validation/status.txt
    
    
  
